[package]
name = "system-gauges"
version = "0.2.0"
edition = "2024"
description = "A tui program that displays information about your system in a gauge format"
homepage = "https://github.com/Djalcoding/system-gauges.rs"
repository = "https://github.com/Djalcoding/system-gauges.rs"
license-file = "LICENSE.txt"
readme = "cratesREADME.md"

[dependencies]
crossterm = "0.29.0"
hex = "0.4.3"
ratatui = "0.30.2"
sysinfo = "0.36.1"
